on: [push]

jobs:
  xrt_centos:
    runs-on: ubuntu-latest
    strategy:
       fail-fast: false
       matrix:
         centos: ["7"]
    container:
      image: centos:${{ matrix.centos }}
      env:
        CC: /opt/rh/devtoolset-9/root/usr/bin/gcc
        CXX: /opt/rh/devtoolset-9/root/usr/bin/g++
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout XRT
      uses: actions/checkout@v2
      with:
        repository: stsoe/XRT
        path: ./xrt
    - name: install dependencies
      run: ./xrt/src/runtime_src/tools/scripts/xrtdeps.sh
    - name: build
      run: |
        PATH="/opt/rh/devtoolset-9/root/usr/bin:${PATH:-}"
        ./xrt/build/build.sh -opt
