name: CMake Build

on:
  pull_request:
    types: [opened, synchronize]
    branches: main

  workflow_dispatch:  

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libelf-dev libboost-dev

    - name: Install Dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        vcpkg install boost-format:x64-windows-static-md

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build/Release -DCMAKE_INSTALL_PREFIX=build/Release

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build/Release --config Release --target install

    - name: Test
      run: |
        ${{github.workspace}}/build/Release/bin/main.exe
