name: Clang-Tidy Review

on:
  pull_request:
    types: [opened, synchronize]
    branches: main
    
  workflow_dispatch:

jobs:
  clangtidy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Fetch base branch
      run: |
        git fetch origin ${{ github.base_ref }}

    - name: Install clang-tidy
      run: |
        sudo apt install -y clang-tidy

    - name: Build and generate compile_commands.json
      run: |
        cmake -B build/Release \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
        -DCMAKE_INSTALL_PREFIX=build/Release
        cmake --build build/Release --config Release

    - name: Run clang-tidy
      run: |
        git diff -U0 origin/${{ github.base_ref }}...HEAD | \
        clang-tidy-diff -p1 -path build -export-fixes build/Release/clang-tidy-fixes.yml

    - name: Post clang-tidy comments
      uses: ZedThree/clang-tidy-review@v0.20.1
      with:
        clang_tidy_fixes: build/Release/clang-tidy-fixes.yml
        github_token: ${{ secrets.GITHUB_TOKEN }}
