on: workflow_dispatch
    
jobs:
  clangtidy:
    runs-on: ubuntu-latest
    # Only run in main repository as Coverity scans are limitted              
    steps:
    - name: Checkout XRT
      uses: actions/checkout@v2
    - name: Store sha
      run: echo ${{ github.sha }} > sha
    - name: Compare sha
      uses: actions/cache@v2
      id: cache-sha
      with:
        path: sha
        key: commit-${{ github.sha }}
    - name: Install dependencies
      if: steps.cache-sha.outputs.cache-hit != 'true'
      run: |
        sudo apt update
        sudo src/runtime_src/tools/scripts/xrtdeps.sh
    - name: Build with clangtidy
      if: steps.cache-sha.outputs.cache-hit != 'true'
      run: |
        build/build.sh -clangtidy -opt |& tee build.clangtidy.log
    - name: Upload Coverity imed
      if: steps.cache-sha.outputs.cache-hit != 'true'
      uses: actions/upload-artifact@v1
      with:
        name: clang tidy build log
        path: build.clangtidy.log
