on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: List linux/version.h
      run: |
        echo ${{ github.sha }} > sha
    - name: Checkout playground
      uses: actions/checkout@v2
    - name: Compare cache
      uses: actions/cache@v2
      id: cache
      with:
        path: sha
        key: commit-${{ github.sha }}
    - name: hit
      if: test.cache.outputs.cache-hit == 'true'
      run: echo "cache hit"
    - name: miss
      if: test.cache.outputs.cache-hit == 'true'
      run: echo "cache miss"
