on:
  workflow_dispatch:
    inputs:
      msg:
        description: input a message
        default: hello
      sha:
        description: Sha of pull request
        default: 0
        required: true

  pull_request:

jobs:
  my_test:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout playground on pull request
      if: github.event_name == 'pull_request'
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Checkout playground on dispatch
      if: github.event_name == 'workflow_dispatch'
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.sha }}

    - name: Run test on pull request
      if: github.event_name == 'pull_request'
      run: echo "pull request test"

    - name: Run test on dispatch
      if: github.event_name == 'workflow_dispatch'
      run: echo "dispatch test"
