on:
  workflow_dispatch:
    inputs:
      msg:
        description: input a message
        default: hello
      sha:
        description: Sha of pull request
        default: 0
        required: true

  pull_request:

jobs:
  my_test:
    runs-on: ubuntu-20.04

    steps:
    if: github.event_name == 'pull_request'
    - name: Checkout playground
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    if: github.event_name == 'workflow_dispatch'
    - name: Checkout playground
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.sha }}
