on: workflow_dispatch

jobs:
  xrt_coverity_scan:
    runs-on: ubuntu-20.04
    steps:
    - name: List linux/version.h
      run: cat /usr/include/linux/version.h
    - name: Checkout playground
      uses: actions/checkout@v2
    - name: Checkout XRT
      run: git clone https://github.com/Xilinx/XRT
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install gcc g++
        sudo ./XRT/src/runtime_src/tools/scripts/xrtdeps.sh
        sudo apt install linux-modules-extra-`uname -r`
    - name: Build
      run: |
        XRT/build/build.sh -opt -verbose -driver
