on: workflow_dispatch

jobs:
  xrt_coverity_scan:
    runs-on: ubuntu-latest
    steps:
    - name: List linux/version.h
      run: cat /usr/include/linux/version.h
    - name: Checkout playground
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        uname -r
        sudo apt install linux-modules-extra-5.4.0-1031-generic
    #   run: |
    #     sudo apt update
    #     sudo apt install gcc g++
    #     sudo ./XRT/src/runtime_src/tools/scripts/xrtdeps.sh
    #     sudo apt install linux-modules-extra-`uname -r`
    # - name: Build
    #   run: |
    #     XRT/build/build.sh -opt -verbose -driver
