on: workflow_dispatch

jobs:
  xrt_job:
    runs-on: windows-2019
    name: A job to retrieve XRT
    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Checkout XRT
      uses: actions/checkout@v2
      with:
        repository: stsoe/XRT
        path: ./xrt
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: install dependencies
      run: |
        python ./xrt/src/runtime_src/tools/scripts/xrtdeps-win.py --icd --opencl
        python ./xrt/src/runtime_src/tools/scripts/xrtdeps-win.py
