on: workflow_dispatch

jobs:
  test:
    runs-on: windows-2019
    name: A test
    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Hello
      run: |
        cmake -G "NMake Makefiles" .
	nmake
