on: [push]

jobs:
  xrt_job:
    runs-on: ubuntu-latest
    name: A job to retrieve XRT
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout XRT
      uses: actions/checkout@v2
      with:
        repository: stsoe/XRT
        path: ./xrt
    - name: version
      run: git version
    - name: find files
      run: find ./xrt -type f
    - name: update
      run: sudo apt update
    - name: install dependencies
      run: sudo ./xrt/src/runtime_src/tools/scripts/xrtdeps.sh
    - name: build
      run: ./xrt/build/build.sh -opt
      
      
